'''Mad Libs Game'''

color= input("Enter a color:")
plural= input("Enter Plural Noun: ")
celebrity= input("Enter Celebrity name:")
print("Roses are " + color )
print(plural + " are blue")
print("I love " + celebrity )

print("Lets try one more...")
noun_number1= input("Enter a Noun; Number:")
noun1= input ("Enter noun:")
adjective1 = input ("Enter adjective:")
noun2=input ("Enter noun:")
adjective2= input ("Enter adjective:")
adjective3= input ("Enter adjective:")
adjective4= input ("Enter adjective:")
adjective5= input ("Enter adjective:")
noun3=input ("Enter noun:")
verb1=input ("Enter verb:")
noun4=input ("Enter noun; type of food:")
noun5=input ("Enter noun; number:")

print("Summer is one of the "+ noun_number1)
print("The other three seasons are "+ noun1)
print(adjective1+ " and "+ noun2 + ". Two major")
print("U.S. summer holidays are "+ adjective2 +" Day")
print("and " + adjective3+" Day. Summer is a(n)")
print(adjective4 + " time of year, when the days")
print(" are "+ adjective5 +" and the "+noun3)
print(verb1 + "s in the sky all day long. One")
print("of the most popular summer treats is ice")
print(noun4+ ", with "+ noun5 +" gallons sold each year.")